const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={page:"dashboard",custom:JSON.parse(localStorage.getItem("yapi360-records")||"{}")};
const icons={dashboard:"▦",projeler:"▣",sozlesmeler:"▤",santiye:"▥",taseronlar:"▧",hakedisler:"₺",satinalma:"▨",depo:"▦",bagimsiz:"⌂",crm:"♙",satis:"₺",raporlar:"▤",ayarlar:"⚙"};
function login(e){e.preventDefault();const email=$("#email").value.trim(),pass=$("#pass").value;$("#loginError").textContent="";if(email==="admin@yapi360.demo"&&pass==="123456"){sessionStorage.setItem("yapi360-auth","1");showApp()}else $("#loginError").textContent="E-posta veya şifre hatalı."}
function showApp(){ $("#login").hidden=true;$("#app").classList.add("visible");renderNav();navigate(location.hash.slice(1)||"dashboard")}
function logout(){sessionStorage.removeItem("yapi360-auth");location.hash="";location.reload()}
function renderNav(){const nav=$("#nav");nav.innerHTML=Object.entries(window.YAPI360_SECTIONS).map(([key,v])=>`<button class="nav-item" data-page="${key}"><span class="nav-icon">${icons[key]}</span><span>${v.title==="Genel Bakış"?"Dashboard":v.title}</span></button>`).join("");nav.addEventListener("click",e=>{const b=e.target.closest("[data-page]");if(b)navigate(b.dataset.page)})}
function navigate(page){if(!window.YAPI360_SECTIONS[page])page="dashboard";state.page=page;history.replaceState(null,"","#"+page);$$(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.page===page));const cfg=window.YAPI360_SECTIONS[page];$("#pageTitle").textContent=cfg.title;$("#pageDescription").textContent=cfg.description;$("#sidebar").classList.remove("open");render()}
function render(){const content=$("#content");if(state.page==="dashboard")content.innerHTML=dashboard();else if(window.YAPI360_SECTIONS[state.page].settings)content.innerHTML=settings();else content.innerHTML=listPage(window.YAPI360_SECTIONS[state.page]);bindPage()}
function dashboard(){return `<div class="grid"><article class="stat"><small>AKTİF PROJE</small><strong>4</strong><em>+1 yeni proje</em></article><article class="stat"><small>TOPLAM SATIŞ</small><strong>₺128,4 Mn</strong><em>↑ %12,4</em></article><article class="stat"><small>TAHSİLAT</small><strong>₺91,2 Mn</strong><em>%71 tahsilat oranı</em></article><article class="stat"><small>ORT. İLERLEME</small><strong>%57</strong><em>Planla uyumlu</em></article></div><div class="panels"><section class="panel"><div class="panel-head"><h3>Aktif Projeler</h3><button class="btn ghost" data-go="projeler">Tümünü Gör</button></div>${[["Şamlar Residence",68],["Kayaşehir Park",52],["Kartal Sahil",41],["Tuzla Karma",67]].map(x=>`<div class="row"><span>${x[0]}<div class="progress"><span style="width:${x[1]}%"></span></div></span><span class="badge">% ${x[1]}</span></div>`).join("")}</section><section class="panel"><h3>Satış Özeti</h3><div class="row"><span>Toplam Ünite</span><b>186</b></div><div class="row"><span>Satılan</span><b>104</b></div><div class="row"><span>Rezerve</span><b>17</b></div><div class="row"><span>Satışta</span><b>65</b></div></section></div>`}
function rowsFor(){return [...(window.YAPI360_SECTIONS[state.page].rows||[]),...(state.custom[state.page]||[])]}
function listPage(cfg){return `<div class="toolbar"><input class="input search" id="search" placeholder="${cfg.title} içinde ara…"><button class="btn gold" id="addRecord">+ Yeni Kayıt</button><button class="btn ghost" id="exportCsv">CSV Dışa Aktar</button></div><div class="table-wrap"><table class="table"><thead><tr>${cfg.columns.map(x=>`<th>${x}</th>`).join("")}<th>İşlem</th></tr></thead><tbody id="tableBody"></tbody></table></div>`}
function renderRows(query=""){const cfg=window.YAPI360_SECTIONS[state.page],rows=rowsFor().filter(r=>r.join(" ").toLocaleLowerCase("tr").includes(query.toLocaleLowerCase("tr")));$("#tableBody").innerHTML=rows.length?rows.map((r,i)=>`<tr>${r.map((c,j)=>`<td>${j===r.length-1?`<span class="badge ${/Gecikme|Kritik|Bekliyor/.test(c)?"warning":""}">${c}</span>`:c}</td>`).join("")}<td><button class="btn danger" data-delete="${i}">Sil</button></td></tr>`).join(""):`<tr><td colspan="${cfg.columns.length+1}" class="empty">Kayıt bulunamadı.</td></tr>`}
function settings(){return `<section class="panel"><h3>Firma Bilgileri</h3><div class="form-grid"><div class="field"><label>Firma adı</label><input class="input" value="Demo İnşaat A.Ş."></div><div class="field"><label>Para birimi</label><select class="select"><option>TRY — Türk Lirası</option></select></div><div class="field"><label>Bildirim e-postası</label><input class="input" value="admin@yapi360.demo"></div><div class="field"><label>Dil</label><select class="select"><option>Türkçe</option></select></div></div><button class="btn" id="saveSettings">Ayarları Kaydet</button></section><section class="panel" style="margin-top:18px"><h3>PWA Durumu</h3><div class="row"><span>Çevrimdışı çalışma</span><span class="badge">Etkin</span></div><div class="row"><span>Uygulama sürümü</span><b>3.0.0</b></div></section>`}
function bindPage(){$$("[data-go]").forEach(x=>x.onclick=()=>navigate(x.dataset.go));if(state.page==="dashboard"||state.page==="ayarlar"){const s=$("#saveSettings");if(s)s.onclick=()=>toast("Ayarlar kaydedildi.");return}renderRows();$("#search").oninput=e=>renderRows(e.target.value);$("#addRecord").onclick=openModal;$("#exportCsv").onclick=exportCsv;$("#tableBody").onclick=e=>{const b=e.target.closest("[data-delete]");if(!b)return;const base=window.YAPI360_SECTIONS[state.page].rows.length,index=Number(b.dataset.delete);if(index<base)return toast("Demo kayıtları korunur.");state.custom[state.page].splice(index-base,1);save();renderRows();toast("Kayıt silindi.")}}
function openModal(){const cfg=window.YAPI360_SECTIONS[state.page];$("#modalTitle").textContent=cfg.title+" — Yeni Kayıt";$("#recordFields").innerHTML=cfg.columns.map((c,i)=>`<div class="field"><label>${c}</label><input class="input" name="f${i}" required></div>`).join("");$("#recordModal").classList.add("open")}
function saveRecord(e){e.preventDefault();const row=[...new FormData(e.target).values()];(state.custom[state.page]??=[]).push(row);save();closeModal();renderRows();toast("Yeni kayıt eklendi.")}
function save(){localStorage.setItem("yapi360-records",JSON.stringify(state.custom))}
function exportCsv(){const cfg=window.YAPI360_SECTIONS[state.page],csv=[cfg.columns,...rowsFor()].map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(";")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv"}));a.download=`yapi360-${state.page}.csv`;a.click();URL.revokeObjectURL(a.href);toast("CSV hazırlandı.")}
function closeModal(){$("#recordModal").classList.remove("open");$("#recordForm").reset()}
function toast(message){const t=$("#toast");t.textContent=message;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}
let deferredPrompt;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;$("#installBtn").style.display="inline-flex"});$("#installBtn").onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$("#installBtn").style.display="none"};window.addEventListener("appinstalled",()=>toast("Yapı360 cihazınıza yüklendi."));
$("#loginForm").addEventListener("submit",login);$("#logoutBtn").onclick=logout;$("#menuToggle").onclick=()=>$("#sidebar").classList.toggle("open");$("#recordForm").addEventListener("submit",saveRecord);$("#closeModal").onclick=closeModal;$("#recordModal").onclick=e=>{if(e.target.id==="recordModal")closeModal()};window.addEventListener("hashchange",()=>navigate(location.hash.slice(1)));if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js"));if(sessionStorage.getItem("yapi360-auth")==="1")showApp();
