const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={page:"dashboard",custom:JSON.parse(localStorage.getItem("yapi360-records")||"{}"),settings:JSON.parse(localStorage.getItem("yapi360-settings")||'{"company":"Demo İnşaat A.Ş.","email":"admin@yapi360.demo","currency":"TRY"}'),audit:JSON.parse(localStorage.getItem("yapi360-audit")||"[]"),editIndex:null,sort:{column:0,direction:1}};
const icons={dashboard:"▦",projeler:"▣",sozlesmeler:"▤",santiye:"▥",taseronlar:"▧",hakedisler:"₺",satinalma:"▨",depo:"▦",bagimsiz:"⌂",crm:"♙",satis:"₺",raporlar:"▤",ayarlar:"⚙"};
function login(e){e.preventDefault();const email=$("#email").value.trim(),pass=$("#pass").value;$("#loginError").textContent="";if(email==="admin@yapi360.demo"&&pass==="123456"){sessionStorage.setItem("yapi360-auth","1");showApp()}else $("#loginError").textContent="E-posta veya şifre hatalı."}
function showApp(){ $("#login").hidden=true;$("#app").classList.add("visible");$(".company").textContent=state.settings.company+" · Admin";renderNav();navigate(location.hash.slice(1)||"dashboard")}
function logout(){sessionStorage.removeItem("yapi360-auth");location.hash="";location.reload()}
function renderNav(){const nav=$("#nav");nav.innerHTML=Object.entries(window.YAPI360_SECTIONS).map(([key,v])=>`<button class="nav-item" data-page="${key}"><span class="nav-icon">${icons[key]}</span><span>${v.title==="Genel Bakış"?"Dashboard":v.title}</span></button>`).join("");nav.addEventListener("click",e=>{const b=e.target.closest("[data-page]");if(b)navigate(b.dataset.page)})}
function navigate(page){if(!window.YAPI360_SECTIONS[page])page="dashboard";state.page=page;history.replaceState(null,"","#"+page);$$(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.page===page));const cfg=window.YAPI360_SECTIONS[page];$("#pageTitle").textContent=cfg.title;$("#pageDescription").textContent=cfg.description;$("#sidebar").classList.remove("open");render()}
function render(){const content=$("#content");if(state.page==="dashboard")content.innerHTML=dashboard();else if(window.YAPI360_SECTIONS[state.page].settings)content.innerHTML=settings();else content.innerHTML=listPage(window.YAPI360_SECTIONS[state.page]);bindPage()}
function dashboard(){return `<div class="grid"><article class="stat"><small>AKTİF PROJE</small><strong>4</strong><em>+1 yeni proje</em></article><article class="stat"><small>TOPLAM SATIŞ</small><strong>₺128,4 Mn</strong><em>↑ %12,4</em></article><article class="stat"><small>TAHSİLAT</small><strong>₺91,2 Mn</strong><em>%71 tahsilat oranı</em></article><article class="stat"><small>ORT. İLERLEME</small><strong>%57</strong><em>Planla uyumlu</em></article></div><div class="panels"><section class="panel"><div class="panel-head"><h3>Aktif Projeler</h3><button class="btn ghost" data-go="projeler">Tümünü Gör</button></div>${[["Şamlar Residence",68],["Kayaşehir Park",52],["Kartal Sahil",41],["Tuzla Karma",67]].map(x=>`<div class="row"><span>${x[0]}<div class="progress"><span style="width:${x[1]}%"></span></div></span><span class="badge">% ${x[1]}</span></div>`).join("")}</section><section class="panel"><h3>Satış Özeti</h3><div class="row"><span>Toplam Ünite</span><b>186</b></div><div class="row"><span>Satılan</span><b>104</b></div><div class="row"><span>Rezerve</span><b>17</b></div><div class="row"><span>Satışta</span><b>65</b></div></section></div>`}
function rowsFor(){return [...(window.YAPI360_SECTIONS[state.page].rows||[]),...(state.custom[state.page]||[])]}
function listPage(cfg){return `<div class="toolbar"><input class="input search" id="search" placeholder="${cfg.title} içinde ara…"><button class="btn gold" id="addRecord">+ Yeni Kayıt</button><button class="btn ghost" id="exportCsv">CSV Dışa Aktar</button></div><div class="table-wrap"><table class="table"><thead><tr>${cfg.columns.map((x,i)=>`<th><button class="sort" data-sort="${i}">${x} ↕</button></th>`).join("")}<th>İşlem</th></tr></thead><tbody id="tableBody"></tbody></table></div>`}
function renderRows(query=""){const cfg=window.YAPI360_SECTIONS[state.page],rows=rowsFor().map((row,index)=>({row,index})).filter(x=>x.row.join(" ").toLocaleLowerCase("tr").includes(query.toLocaleLowerCase("tr"))).sort((a,b)=>String(a.row[state.sort.column]).localeCompare(String(b.row[state.sort.column]),"tr",{numeric:true})*state.sort.direction);$("#tableBody").innerHTML=rows.length?rows.map(({row:r,index:i})=>`<tr>${r.map((c,j)=>`<td>${j===r.length-1?`<span class="badge ${/Gecikme|Kritik|Bekliyor/.test(c)?"warning":""}">${c}</span>`:c}</td>`).join("")}<td><div class="actions"><button class="btn ghost small" data-edit="${i}">Düzenle</button><button class="btn danger small" data-delete="${i}">Sil</button></div></td></tr>`).join(""):`<tr><td colspan="${cfg.columns.length+1}" class="empty">Kayıt bulunamadı.</td></tr>`}
function settings(){return `<form class="panel" id="settingsForm"><h3>Firma Bilgileri</h3><div class="form-grid"><div class="field"><label>Firma adı</label><input class="input" name="company" value="${escapeHtml(state.settings.company)}" required></div><div class="field"><label>Para birimi</label><select class="select" name="currency"><option value="TRY">TRY — Türk Lirası</option><option value="USD">USD — ABD Doları</option><option value="EUR">EUR — Euro</option></select></div><div class="field"><label>Bildirim e-postası</label><input class="input" type="email" name="email" value="${escapeHtml(state.settings.email)}" required></div><div class="field"><label>Dil</label><select class="select"><option>Türkçe</option></select></div></div><button class="btn" type="submit">Ayarları Kaydet</button></form><section class="panel" style="margin-top:18px"><div class="panel-head"><h3>Veri Yönetimi</h3><span class="badge">Yerel ve çevrimdışı</span></div><div class="toolbar"><button class="btn ghost" id="backupData">JSON Yedeği İndir</button><label class="btn ghost" for="restoreData">Yedekten Geri Yükle</label><input id="restoreData" type="file" accept="application/json" hidden></div></section><section class="panel" style="margin-top:18px"><h3>Son İşlemler</h3>${state.audit.length?state.audit.slice(0,5).map(x=>`<div class="row"><span>${escapeHtml(x.message)}</span><small>${new Date(x.time).toLocaleString("tr-TR")}</small></div>`).join(""):'<div class="empty">Henüz işlem bulunmuyor.</div>'}</section>`}
function bindPage(){$("[data-go]").forEach(x=>x.onclick=()=>navigate(x.dataset.go));if(state.page==="dashboard")return;if(state.page==="ayarlar"){$("#settingsForm").onsubmit=saveSettings;$("#backupData").onclick=backupData;$("#restoreData").onchange=restoreData;return}renderRows();$("#search").oninput=e=>renderRows(e.target.value);$("#addRecord").onclick=()=>openModal();$("#exportCsv").onclick=exportCsv;$("[data-sort]").forEach(b=>b.onclick=()=>{const c=Number(b.dataset.sort);state.sort.direction=state.sort.column===c?-state.sort.direction:1;state.sort.column=c;renderRows($("#search").value)});$("#tableBody").onclick=e=>{const edit=e.target.closest("[data-edit]"),del=e.target.closest("[data-delete]");if(edit)return openModal(Number(edit.dataset.edit));if(!del)return;const base=window.YAPI360_SECTIONS[state.page].rows.length,index=Number(del.dataset.delete);if(index<base)return toast("Demo kayıtları korunur.");if(!confirm("Bu kaydı silmek istediğinize emin misiniz?"))return;state.custom[state.page].splice(index-base,1);audit("Kayıt silindi: "+state.page);save();renderRows();toast("Kayıt silindi.")}}
function openModal(index=null){const cfg=window.YAPI360_SECTIONS[state.page],row=index===null?[]:rowsFor()[index];state.editIndex=index;$("#modalTitle").textContent=cfg.title+(index===null?" — Yeni Kayıt":" — Kayıt Düzenle");$("#recordFields").innerHTML=cfg.columns.map((c,i)=>`<div class="field"><label>${c}</label><input class="input" name="f${i}" value="${escapeHtml(row?.[i]||"")}" required></div>`).join("");$("#recordModal").classList.add("open")}
function saveRecord(e){e.preventDefault();const row=[...new FormData(e.target).values()],base=window.YAPI360_SECTIONS[state.page].rows.length,wasEdit=state.editIndex!==null;if(state.editIndex===null){(state.custom[state.page]??=[]).push(row);audit("Yeni kayıt eklendi: "+state.page)}else if(state.editIndex<base){(state.custom[state.page]??=[]).push(row);audit("Demo kaydından yeni kayıt oluşturuldu: "+state.page)}else{state.custom[state.page][state.editIndex-base]=row;audit("Kayıt güncellendi: "+state.page)}save();closeModal();renderRows();toast(wasEdit?"Kayıt güncellendi.":"Yeni kayıt eklendi.")}
function save(){localStorage.setItem("yapi360-records",JSON.stringify(state.custom));localStorage.setItem("yapi360-audit",JSON.stringify(state.audit))}
function audit(message){state.audit.unshift({message,time:new Date().toISOString()});state.audit=state.audit.slice(0,50)}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function saveSettings(e){e.preventDefault();state.settings=Object.fromEntries(new FormData(e.target));localStorage.setItem("yapi360-settings",JSON.stringify(state.settings));$(".company").textContent=state.settings.company+" · Admin";audit("Firma ayarları güncellendi");save();toast("Ayarlar kaydedildi.")}
function backupData(){const payload={version:1,exportedAt:new Date().toISOString(),records:state.custom,settings:state.settings,audit:state.audit};const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:"application/json"}));a.download="yapi360-yedek-"+new Date().toISOString().slice(0,10)+".json";a.click();URL.revokeObjectURL(a.href);toast("Yedek indirildi.")}
async function restoreData(e){const file=e.target.files[0];if(!file)return;try{const payload=JSON.parse(await file.text());if(payload.version!==1||!payload.records)throw new Error("Geçersiz yedek");state.custom=payload.records;state.settings=payload.settings||state.settings;state.audit=payload.audit||[];audit("Veriler yedekten geri yüklendi");save();localStorage.setItem("yapi360-settings",JSON.stringify(state.settings));render();toast("Yedek başarıyla yüklendi.")}catch{toast("Yedek dosyası geçersiz.")}e.target.value=""}
function exportCsv(){const cfg=window.YAPI360_SECTIONS[state.page],csv=[cfg.columns,...rowsFor()].map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(";")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv"}));a.download=`yapi360-${state.page}.csv`;a.click();URL.revokeObjectURL(a.href);toast("CSV hazırlandı.")}
function closeModal(){$("#recordModal").classList.remove("open");$("#recordForm").reset();state.editIndex=null}
function toast(message){const t=$("#toast");t.textContent=message;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}
let deferredPrompt;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;$("#installBtn").style.display="inline-flex"});$("#installBtn").onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$("#installBtn").style.display="none"};window.addEventListener("appinstalled",()=>toast("Yapı360 cihazınıza yüklendi."));
$("#loginForm").addEventListener("submit",login);$("#logoutBtn").onclick=logout;$("#menuToggle").onclick=()=>$("#sidebar").classList.toggle("open");$("#recordForm").addEventListener("submit",saveRecord);$("#closeModal").onclick=closeModal;$("#recordModal").onclick=e=>{if(e.target.id==="recordModal")closeModal()};window.addEventListener("hashchange",()=>navigate(location.hash.slice(1)));if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js"));if(sessionStorage.getItem("yapi360-auth")==="1")showApp();
