window.YAPI360_SECTIONS = {
dashboard:{title:"Genel Bakış",description:"Projeler, finans ve satış performansının güncel özeti."},
projeler:{title:"Projeler",description:"Aktif ve planlanan projelerin süre, bütçe ve ilerleme takibi.",columns:["Proje","Konum","Durum","İlerleme","Bütçe"],rows:[["Şamlar Residence","Başakşehir","Aktif","%68","₺480 Mn"],["Kayaşehir Park","Kayaşehir","Aktif","%52","₺325 Mn"],["Kartal Sahil","Kartal","Aktif","%41","₺610 Mn"],["Tuzla Karma","Tuzla","Planlı","%12","₺275 Mn"]]},
sozlesmeler:{title:"Sözleşmeler",description:"Arsa sahibi, satış ve tedarik sözleşmelerinin merkezi takibi.",columns:["Sözleşme","Taraf","Proje","Tarih","Durum"],rows:[["Arsa Payı Karşılığı","Yıldız Ailesi","Şamlar Residence","12.03.2026","İmzalandı"],["Kaba İnşaat","ABC Yapı","Kayaşehir Park","04.06.2026","Aktif"],["Satış Sözleşmesi","Ayşe Demir","Kartal Sahil","21.08.2026","Taslak"]]},
santiye:{title:"Şantiye",description:"İş programı, günlük rapor ve fiziksel ilerleme yönetimi.",columns:["İş Kalemi","Proje","Sorumlu","Plan","Gerçekleşen"],rows:[["Betonarme","Şamlar Residence","Mehmet Kaya","%74","%68"],["Mekanik","Kayaşehir Park","Ece Teknik","%56","%52"],["Cephe","Kartal Sahil","Nova Cephe","%45","%41"]]},
taseronlar:{title:"Taşeronlar",description:"Taşeron sözleşmeleri, cari durum ve performans takibi.",columns:["Firma","Uzmanlık","Proje","Sözleşme","Bakiye"],rows:[["ABC Kalıp Ltd.","Kalıp","Şamlar Residence","₺12,5 Mn","₺7,5 Mn"],["Ece Teknik","Mekanik","Kayaşehir Park","₺8,2 Mn","₺3,1 Mn"],["Nova Cephe","Cephe","Kartal Sahil","₺14,8 Mn","₺9,4 Mn"]]},
hakedisler:{title:"Hakedişler",description:"Hakediş hazırlama, onay ve ödeme akışları.",columns:["No","Taşeron","Dönem","Tutar","Durum"],rows:[["HK-2026-018","ABC Kalıp Ltd.","Ağustos 2026","₺1,25 Mn","Onay Bekliyor"],["HK-2026-017","Ece Teknik","Ağustos 2026","₺680 Bin","Onaylandı"],["HK-2026-016","Nova Cephe","Temmuz 2026","₺940 Bin","Ödendi"]]},
satinalma:{title:"Satın Alma",description:"Talep, teklif karşılaştırma ve sipariş süreci.",columns:["Talep","Malzeme","Proje","Tutar","Durum"],rows:[["ST-1042","120 ton nervürlü demir","Şamlar Residence","₺3,72 Mn","Teklif Seçildi"],["ST-1041","Seramik 3.400 m²","Kayaşehir Park","₺1,18 Mn","Teklif Toplanıyor"],["ST-1040","Elektrik kablosu","Kartal Sahil","₺560 Bin","Sipariş"]]},
depo:{title:"Depo / Stok",description:"Şantiye bazlı stok giriş, çıkış ve kritik seviye kontrolü.",columns:["Malzeme","Depo","Mevcut","Birim","Durum"],rows:[["Nervürlü Demir","Şamlar Ana Depo","42","ton","Yeterli"],["Çimento","Kayaşehir Depo","180","torba","Kritik"],["Seramik","Kartal Depo","2.150","m²","Yeterli"]]},
bagimsiz:{title:"Bağımsız Bölümler",description:"Daire ve ticari ünitelerin durum, fiyat ve malik bilgileri.",columns:["Ünite","Proje","Tip","Brüt m²","Durum"],rows:[["A-15","Şamlar Residence","3+1","145","Satışta"],["B-18","Şamlar Residence","2+1","108","Rezerve"],["C-08","Kayaşehir Park","Dükkan","220","Satıldı"]]},
crm:{title:"CRM",description:"Müşteri adayları, görüşmeler ve satış fırsatları.",columns:["Müşteri","İlgilendiği Proje","Bütçe","Son Görüşme","Aşama"],rows:[["Ahmet Yılmaz","Şamlar Residence","₺15 Mn","28.08.2026","Teklif"],["Selin Aksoy","Kartal Sahil","₺22 Mn","27.08.2026","Proje Ziyareti"],["Mert Can","Kayaşehir Park","₺12 Mn","25.08.2026","Yeni"]]},
satis:{title:"Satış & Tahsilat",description:"Satış sözleşmeleri, ödeme planları ve tahsilat durumu.",columns:["Müşteri","Ünite","Satış Bedeli","Tahsil Edilen","Durum"],rows:[["Ayşe Demir","A-15","₺15 Mn","₺8,2 Mn","Devam Ediyor"],["Can Kaya","C-08","₺21 Mn","₺21 Mn","Tamamlandı"],["Deniz Aras","B-18","₺13,5 Mn","₺2,7 Mn","Gecikme"]]},
raporlar:{title:"Raporlar",description:"Yönetim, maliyet, satış ve tahsilat raporları.",columns:["Rapor","Dönem","Son Güncelleme","Format","Durum"],rows:[["Proje Karlılık","2026","30.08.2026","PDF / CSV","Hazır"],["Satış Performansı","Ağustos 2026","30.08.2026","CSV","Hazır"],["Nakit Akışı","Q3 2026","29.08.2026","PDF","Hazır"]]},
ayarlar:{title:"Ayarlar",description:"Firma, kullanıcı, yetki ve uygulama tercihleri.",settings:true}
};
